In [33]:
import pandas as pd
import collections

In [46]:
sc_dic = collections.defaultdict(list)

with open('log.txt') as f:
    for l in f:
        if 'Initiating scan' in l:
            smpInfo = next(f)
            smpInfo = smpInfo.replace('\n',' ')
            print(smpInfo)
            parmInfo = next(f)
            parmInfo = parmInfo.split('\t')
            parmInfo[0] = parmInfo[0][21:]
            
            sc = l[l.index('_')+1:l.index('.')]
            smpInfo = smpInfo[smpInfo.index(':'):]
            sc_dic['scan_number'].append(sc)
            sc_dic['smp_info'].append(smpInfo)
            for p_ in parmInfo:
                if p_ != '\n':
                    t = p_.split(':')
                    sc_dic[t[0]].append(float(t[1]))

Sample info: Tube 1-3
Sample info: Tube 1-3
Sample info: Tube 1-3
Sample info: Tube 1-3
Sample info: Tube 1-3
Sample info: Tube 1-3
Sample info: Tube 1-3
Sample info: Tube 1-3
Sample info: Tube 1-3
Sample info: Tube 2-2
Sample info: Tube 2-2
Sample info: Tube 2-2

In [47]:
sc_pd = pd.DataFrame(sc_dic)

In [48]:
sc_pd

,scan_number,smp_info,x_width,y_width,x_step,y_step,dwell,x_center_Rqs,y_center_Rqs,z_value_Rqs
0,fly0302,: Tube 1-3,80.0,200.0,2.0,2.0,50.0,803.116,-354.0,301.069
1,fly0002,: Tube 1-3,80.0,200.0,2.0,2.0,50.0,628.939,-354.0,358.092
2,fly0003,: Tube 1-3,80.0,200.0,2.0,2.0,50.0,879.133,-1118.0,306.582
3,fly0004,: Tube 1-3,80.0,200.0,2.0,2.0,50.0,704.956,-1118.0,363.605
4,fly0012,: Tube 1-3,80.0,80.0,2.0,2.0,50.0,292.178,-1245.0,469.033
5,fly0013,: Tube 1-3,80.0,80.0,2.0,2.0,50.0,-80.323,-820.0,589.549
6,fly0014,: Tube 1-3,80.0,80.0,2.0,2.0,50.0,52.919,-720.0,507.260
7,fly0015,: Tube 1-3,58.0,56.0,0.5,0.5,50.0,302.000,-1241.0,469.000
8,fly0016,: Tube 1-3,60.0,60.0,0.5,0.5,50.0,-48.000,-848.0,589.500
9,fly0017,: Tube 2-2,54.0,54.0,0.1,0.1,60.0,-52.250,-847.0,589.500
10,fly0018,: Tube 2-2,54.0,54.0,0.1,0.1,60.0,-52.250,-847.0,589.500
11,fly0019,: Tube 2-2,56.0,52.0,0.1,0.1,60.0,302.250,-1240.0,469.000